{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python3",
   "display_name": "Python 3.8.5 64-bit ('base': conda)",
   "metadata": {
    "interpreter": {
     "hash": "61c0736e115877655d96e5cac599358ade349d90be5b961d5f76753eb05f6b7c"
    }
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 104,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import json\n",
    "from pykrx import stock\n",
    "from datetime import date, datetime, timedelta\n",
    "import pandas as pd\n",
    "def post_message(channel, text): \n",
    "    SLACK_BOT_TOKEN = \"\"\n",
    "    headers = {\n",
    "        'Content-Type': 'application/json', \n",
    "        'Authorization': 'Bearer ' + SLACK_BOT_TOKEN\n",
    "        }\n",
    "    payload = {\n",
    "        'channel': channel,\n",
    "        'text': text\n",
    "        }\n",
    "    r = requests.post('https://slack.com/api/chat.postMessage', \n",
    "        headers=headers, \n",
    "        data=json.dumps(payload)\n",
    "        )\n",
    "to_day = date.today().isoformat().replace('-', '')\n",
    "df = stock.get_market_ohlcv_by_date(\"20210320\",to_day, \"252670\", \"d\")\n",
    "df = pd.DataFrame(df)\n",
    "text  = df.iloc[-1][3]\n",
    "text2 = int(text)*9466 - 21239545\n",
    "a = int(df.iloc[-1][3])\n",
    "b = int(df.iloc[-2][3])\n",
    "c = round((a - b) / a * 100,2)\n",
    "post_message(\"financefroject\", '현제가 :'+format(text, ',')+'원 ('+format(c, ',')+'%)'+ '\\n보유수량 :9,466주'+'\\n손익 :'+format(text2, ',')+'원')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "2195\n2175\n"
     ]
    }
   ],
   "source": [
    "print(df.iloc[-1][3])\n",
    "print(df.iloc[-2][3] )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "0.91"
      ]
     },
     "metadata": {},
     "execution_count": 90
    }
   ],
   "source": [
    "a = int(df.iloc[-1][3])\n",
    "b = int(df.iloc[-2][3])\n",
    "c = round((a - b) / a * 100,2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "0.009111617312072893"
      ]
     },
     "metadata": {},
     "execution_count": 88
    }
   ],
   "source": [
    "(2195 - 2175 ) /2195format(1493500, ',')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "              시가    고가    저가    종가        거래량\n",
       "날짜                                           \n",
       "2021-03-22  2130  2170  2115  2130  314860928\n",
       "2021-03-23  2105  2180  2095  2175  265538876\n",
       "2021-03-24  2200  2230  2175  2195  331042959"
      ],
      "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>시가</th>\n      <th>고가</th>\n      <th>저가</th>\n      <th>종가</th>\n      <th>거래량</th>\n    </tr>\n    <tr>\n      <th>날짜</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2021-03-22</th>\n      <td>2130</td>\n      <td>2170</td>\n      <td>2115</td>\n      <td>2130</td>\n      <td>314860928</td>\n    </tr>\n    <tr>\n      <th>2021-03-23</th>\n      <td>2105</td>\n      <td>2180</td>\n      <td>2095</td>\n      <td>2175</td>\n      <td>265538876</td>\n    </tr>\n    <tr>\n      <th>2021-03-24</th>\n      <td>2200</td>\n      <td>2230</td>\n      <td>2175</td>\n      <td>2195</td>\n      <td>331042959</td>\n    </tr>\n  </tbody>\n</table>\n</div>"
     },
     "metadata": {},
     "execution_count": 67
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "0.911"
      ]
     },
     "metadata": {},
     "execution_count": 86
    }
   ],
   "source": [
    "round((int(df.iloc[-1][3]) - int(df.iloc[-2][3])) / int(df.iloc[-1][3]) * 100, 3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 106,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "              시가    고가    저가    종가        거래량\n",
       "날짜                                           \n",
       "2021-03-22  2130  2170  2115  2130  314860928\n",
       "2021-03-23  2105  2180  2095  2175  265538876\n",
       "2021-03-24  2200  2230  2175  2195  331042959"
      ],
      "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>시가</th>\n      <th>고가</th>\n      <th>저가</th>\n      <th>종가</th>\n      <th>거래량</th>\n    </tr>\n    <tr>\n      <th>날짜</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2021-03-22</th>\n      <td>2130</td>\n      <td>2170</td>\n      <td>2115</td>\n      <td>2130</td>\n      <td>314860928</td>\n    </tr>\n    <tr>\n      <th>2021-03-23</th>\n      <td>2105</td>\n      <td>2180</td>\n      <td>2095</td>\n      <td>2175</td>\n      <td>265538876</td>\n    </tr>\n    <tr>\n      <th>2021-03-24</th>\n      <td>2200</td>\n      <td>2230</td>\n      <td>2175</td>\n      <td>2195</td>\n      <td>331042959</td>\n    </tr>\n  </tbody>\n</table>\n</div>"
     },
     "metadata": {},
     "execution_count": 106
    }
   ],
   "source": [
    "stock.get_market_ohlcv_by_date(\"20210320\",'20210325', \"252670\", \"d\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import json\n",
    "from pykrx import stock\n",
    "from datetime import date\n",
    "import datetime\n",
    "import pandas as pd\n",
    "def post_message(channel, text):\n",
    "    SLACK_BOT_TOKEN = \"xoxb-1772521948405-1768837892838-uj4QJb6uTb7hLfjlgby51MVm\"\n",
    "    headers = {\n",
    "        'Content-Type': 'application/json',\n",
    "        'Authorization': 'Bearer ' + SLACK_BOT_TOKEN\n",
    "        }\n",
    "    payload = {\n",
    "        'channel': channel,\n",
    "        'text': text\n",
    "        }\n",
    "    r = requests.post('https://slack.com/api/chat.postMessage',\n",
    "        headers=headers,\n",
    "        data=json.dumps(payload)\n",
    "        )\n",
    "\n",
    "now = datetime.datetime.now()\n",
    "if now.hour >=9 and now.hour <= 15:\n",
    "    if now.hour ==15 and now.minute >= 31:\n",
    "        z = 1\n",
    "    else:\n",
    "        to_day = date.today().isoformat().replace('-', '')\n",
    "        # 인버스 구매단가, 구매 총량 \n",
    "        in_a = 9466\n",
    "        in_b = 21239545\n",
    "        # 레버리지 구매단가, 구매 총량 \n",
    "        ra_a = 854\n",
    "        ra_b = 22127140\n",
    "        df_inv = stock.get_market_ohlcv_by_date(\"20210320\",to_day, \"252670\", \"d\")\n",
    "        df_rvg = stock.get_market_ohlcv_by_date(\"20210320\",to_day, \"122630\", \"d\")\n",
    "        stock_gbn = None\n",
    "        if stock_gbn == 1:\n",
    "            df = df_inv\n",
    "            df_a = in_a\n",
    "            df_b = in_b\n",
    "        else:\n",
    "            df = df_rvg\n",
    "            df_a = ra_a\n",
    "            df_b = ra_b\n",
    "        \n",
    "        df = pd.DataFrame(df)\n",
    "        text  = df.iloc[-1][3]\n",
    "        text2 = int(text)*df_a - df_b\n",
    "        a = int(df.iloc[-1][3])\n",
    "        b = int(df.iloc[-2][3])\n",
    "        c = round((a - b) / a * 100,2)\n",
    "        post_message(\"financefroject\", '현제가 :'+format(text, ',')+'원 ('+format(c, ',')+'%)'+'\\n손익 :'+format(text2, ',')+'원')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "시가        25740\n",
       "고가        26045\n",
       "저가        25635\n",
       "종가        26040\n",
       "거래량    21119536\n",
       "Name: 2021-03-26 00:00:00, dtype: int32"
      ]
     },
     "metadata": {},
     "execution_count": 26
    }
   ],
   "source": [
    "\n",
    "        df_rvg = stock.get_market_ohlcv_by_date(\"20210320\",to_day, \"122630\", \"d\")\n",
    "        df_rvg.iloc[-1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Collecting pymysql\n",
      "  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)\n",
      "\u001b[K     |████████████████████████████████| 43 kB 176 kB/s \n",
      "\u001b[?25hInstalling collected packages: pymysql\n",
      "Successfully installed pymysql-1.0.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install pymysql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pymysql\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "output_type": "error",
     "ename": "AttributeError",
     "evalue": "'NoneType' object has no attribute 'encoding'",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-8-1c1c735c9ecb>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mconn\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpymysql\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mhost\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'3.36.94.44'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0muser\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'root'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdatabase\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'mysql'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpassword\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'kdk3203t7!'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcharset\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'utf-8'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m     \u001b[0mcurs\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcursor\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0msql\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'select 1+1 '\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pymysql/connections.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, user, password, host, database, unix_socket, port, charset, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)\u001b[0m\n\u001b[1;32m    309\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0muse_unicode\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0muse_unicode\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    310\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 311\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mencoding\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcharset_by_name\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcharset\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mencoding\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    312\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    313\u001b[0m         \u001b[0mclient_flag\u001b[0m \u001b[0;34m|=\u001b[0m \u001b[0mCLIENT\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mCAPABILITIES\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'NoneType' object has no attribute 'encoding'"
     ]
    }
   ],
   "source": [
    "conn = pymysql.connect(host='3.36.94.44', user='root', database='mysql', password='kdk3203t7!', charset='utf-8')\n",
    "\n",
    "try:\n",
    "    curs = conn.cursor()\n",
    "    sql = 'select 1+1 '\n",
    "    curs.execute(sql)\n",
    "    rs = curs.fetchall()\n",
    "    for row in rs:\n",
    "        print(row)\n",
    "finally:\n",
    "    conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "output_type": "error",
     "ename": "NameError",
     "evalue": "name 'conn' is not defined",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-9-6e27011b9c0d>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      6\u001b[0m     \u001b[0mcharset\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'utf8'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m )\n\u001b[0;32m----> 8\u001b[0;31m \u001b[0;32mwith\u001b[0m \u001b[0mconn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcursor\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mcurs\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      9\u001b[0m         \u001b[0msql_query\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"select 1+1\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     10\u001b[0m         \u001b[0mcurs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexecute\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msql_query\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'conn' is not defined"
     ]
    }
   ],
   "source": [
    "\n",
    "juso_db = pymysql.connect(\n",
    "    user='seokjin', \n",
    "    passwd='1234', \n",
    "    host='3.36.94.44', \n",
    "    db='stock', \n",
    "    charset='utf8'\n",
    ")\n",
    "with conn.cursor() as curs:\n",
    "        sql_query = \"select 1+1\"\n",
    "        curs.execute(sql_query)\n",
    "        result = curs.fetchall()\n",
    "        df = pd.DataFrame(result)\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "1\n"
     ]
    }
   ],
   "source": [
    "conn = pymysql.connect(\n",
    "    user='seokjin', \n",
    "    passwd='1234', \n",
    "    host='3.36.94.44', \n",
    "    db='stock', \n",
    "    charset='utf8'\n",
    ")\n",
    "cur = conn.cursor()\n",
    "try:\n",
    "    with conn.cursor() as curs:\n",
    "        sql_query = \"show tables\"\n",
    "        print(curs.execute(sql_query))\n",
    "        result = curs.fetchall()\n",
    "        df = pd.DataFrame(result)\n",
    "except:\n",
    "\tprint(\"{} error\".format(sql_query))\n",
    "finally:\n",
    "    conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "    0\n",
       "0  t1"
      ],
      "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>0</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>t1</td>\n    </tr>\n  </tbody>\n</table>\n</div>"
     },
     "metadata": {},
     "execution_count": 30
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "('10',)\n"
     ]
    }
   ],
   "source": [
    "conn = pymysql.connect(\n",
    "    user='seokjin', \n",
    "    passwd='1234', \n",
    "    host='3.36.94.44', \n",
    "    db='stock', \n",
    "    charset='utf8'\n",
    ")\n",
    "\n",
    "try:\n",
    "    curs = conn.cursor()\n",
    "    sql = 'select * from t1 '\n",
    "    curs.execute(sql)\n",
    "    rs = curs.fetchall()\n",
    "    df =\n",
    "finally:\n",
    "    conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "tags": [
     "outputPrepend"
    ]
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "y egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading mysqlclient-1.3.4.tar.gz (77 kB)\n",
      "\u001b[K     |████████████████████████████████| 77 kB 632 kB/s \n",
      "\u001b[?25h\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/seokjinlim/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_41e19c5958ce42f0a804bfbf37fa12da/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_41e19c5958ce42f0a804bfbf37fa12da/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-pip-egg-info-n7_3e66i\n",
      "         cwd: /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_41e19c5958ce42f0a804bfbf37fa12da/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_41e19c5958ce42f0a804bfbf37fa12da/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_41e19c5958ce42f0a804bfbf37fa12da/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_41e19c5958ce42f0a804bfbf37fa12da/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/17/d9/03b08e6a033401335b720806b87596aee8d7f7aa87539713238905c4a8d1/mysqlclient-1.3.4.tar.gz#sha256=a0263383f8ac33ad12d68dc61fa8ccbee41244ce916287c6cee71bf8aea82c5c (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading mysqlclient-1.3.3.tar.gz (77 kB)\n",
      "\u001b[K     |████████████████████████████████| 77 kB 633 kB/s \n",
      "\u001b[?25h\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/seokjinlim/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_f81ea7d26a2e431c9b5160c4d72e1007/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_f81ea7d26a2e431c9b5160c4d72e1007/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-pip-egg-info-4tu5gdep\n",
      "         cwd: /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_f81ea7d26a2e431c9b5160c4d72e1007/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_f81ea7d26a2e431c9b5160c4d72e1007/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_f81ea7d26a2e431c9b5160c4d72e1007/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_f81ea7d26a2e431c9b5160c4d72e1007/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/26/53/c575db342bfca0213c9243ed2642bfadcd420b18d2f477dc812543e3d83a/mysqlclient-1.3.3.tar.gz#sha256=0f0887882d71bf2a079d9724d9323053cfbee8ab2dcfc989daf97d7ce5be9af9 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading mysqlclient-1.3.2.tar.gz (77 kB)\n",
      "\u001b[K     |████████████████████████████████| 77 kB 834 kB/s \n",
      "\u001b[?25h\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/seokjinlim/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_64a29c68b33c41beb349467f5a3e1ecb/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_64a29c68b33c41beb349467f5a3e1ecb/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-pip-egg-info-olw4gpvr\n",
      "         cwd: /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_64a29c68b33c41beb349467f5a3e1ecb/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_64a29c68b33c41beb349467f5a3e1ecb/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_64a29c68b33c41beb349467f5a3e1ecb/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_64a29c68b33c41beb349467f5a3e1ecb/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2d/df/5440ee86bbb248325cdd6e1fc9cbbba365018a0d2d57f673610e020e6b1d/mysqlclient-1.3.2.tar.gz#sha256=e44025830501b9f70f8c2fe8eeff66f0df2df198802f7295801dac199b8236ef (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading mysqlclient-1.3.1.tar.gz (76 kB)\n",
      "\u001b[K     |████████████████████████████████| 76 kB 923 kB/s \n",
      "\u001b[?25h\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/seokjinlim/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_84aa7c060d4b4e55b0348b229b00f3eb/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_84aa7c060d4b4e55b0348b229b00f3eb/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-pip-egg-info-hdlkqsxr\n",
      "         cwd: /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_84aa7c060d4b4e55b0348b229b00f3eb/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_84aa7c060d4b4e55b0348b229b00f3eb/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_84aa7c060d4b4e55b0348b229b00f3eb/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_84aa7c060d4b4e55b0348b229b00f3eb/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6b/ba/4729d99e85a0a35bb46d55500570de05b4af10431cef174b6da9f58a0e50/mysqlclient-1.3.1.tar.gz#sha256=3549e8a61f10c8cd8eac6581d3f44d0594f535fb7b29e6090db3a0bc547b25ad (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading mysqlclient-1.3.0.tar.gz (76 kB)\n",
      "\u001b[K     |████████████████████████████████| 76 kB 1.0 MB/s \n",
      "\u001b[?25h\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/seokjinlim/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_fe69f33e1f974061b511ccb75ff0c4be/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_fe69f33e1f974061b511ccb75ff0c4be/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-pip-egg-info-eok_gj53\n",
      "         cwd: /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_fe69f33e1f974061b511ccb75ff0c4be/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_fe69f33e1f974061b511ccb75ff0c4be/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_fe69f33e1f974061b511ccb75ff0c4be/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysqlclient_fe69f33e1f974061b511ccb75ff0c4be/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6a/91/bdfe808fb5dc99a5f65833b370818161b77ef6d1e19b488e4c146ab615aa/mysqlclient-1.3.0.tar.gz#sha256=06eb5664e3738b283ea2262ee60ed83192e898f019cc7ff251f4d05a564ab3b7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "Collecting mysql\n",
      "  Downloading mysql-0.0.1.tar.gz (1.7 kB)\n",
      "Collecting MySQL-python\n",
      "  Downloading MySQL-python-1.2.5.zip (108 kB)\n",
      "\u001b[K     |████████████████████████████████| 108 kB 1.1 MB/s \n",
      "\u001b[?25h\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/seokjinlim/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_2e34d1fbbb704a46a184a116d9983387/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_2e34d1fbbb704a46a184a116d9983387/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-pip-egg-info-lz3909t2\n",
      "         cwd: /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_2e34d1fbbb704a46a184a116d9983387/\n",
      "    Complete output (7 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_2e34d1fbbb704a46a184a116d9983387/setup.py\", line 13, in <module>\n",
      "        from setup_posix import get_config\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_2e34d1fbbb704a46a184a116d9983387/setup_posix.py\", line 2, in <module>\n",
      "        from ConfigParser import SafeConfigParser\n",
      "    ModuleNotFoundError: No module named 'ConfigParser'\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip#sha256=811040b647e5d5686f84db415efd697e6250008b112b6909ba77ac059e140c74 (from https://pypi.org/simple/mysql-python/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading MySQL-python-1.2.4.zip (113 kB)\n",
      "\u001b[K     |████████████████████████████████| 113 kB 1.1 MB/s \n",
      "\u001b[?25h\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/seokjinlim/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_552eb1ac25014c7eb112e04c2fd7db1d/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_552eb1ac25014c7eb112e04c2fd7db1d/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-pip-egg-info-h3w1i0xf\n",
      "         cwd: /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_552eb1ac25014c7eb112e04c2fd7db1d/\n",
      "    Complete output (31 lines):\n",
      "    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz\n",
      "    Traceback (most recent call last):\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_552eb1ac25014c7eb112e04c2fd7db1d/distribute_setup.py\", line 143, in use_setuptools\n",
      "        raise ImportError\n",
      "    ImportError\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_552eb1ac25014c7eb112e04c2fd7db1d/setup.py\", line 7, in <module>\n",
      "        use_setuptools()\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_552eb1ac25014c7eb112e04c2fd7db1d/distribute_setup.py\", line 145, in use_setuptools\n",
      "        return _do_download(version, download_base, to_dir, download_delay)\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_552eb1ac25014c7eb112e04c2fd7db1d/distribute_setup.py\", line 123, in _do_download\n",
      "        tarball = download_setuptools(version, download_base,\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_552eb1ac25014c7eb112e04c2fd7db1d/distribute_setup.py\", line 194, in download_setuptools\n",
      "        src = urlopen(url)\n",
      "      File \"/Users/seokjinlim/opt/anaconda3/lib/python3.8/urllib/request.py\", line 222, in urlopen\n",
      "        return opener.open(url, data, timeout)\n",
      "      File \"/Users/seokjinlim/opt/anaconda3/lib/python3.8/urllib/request.py\", line 531, in open\n",
      "        response = meth(req, response)\n",
      "      File \"/Users/seokjinlim/opt/anaconda3/lib/python3.8/urllib/request.py\", line 640, in http_response\n",
      "        response = self.parent.error(\n",
      "      File \"/Users/seokjinlim/opt/anaconda3/lib/python3.8/urllib/request.py\", line 569, in error\n",
      "        return self._call_chain(*args)\n",
      "      File \"/Users/seokjinlim/opt/anaconda3/lib/python3.8/urllib/request.py\", line 502, in _call_chain\n",
      "        result = func(*args)\n",
      "      File \"/Users/seokjinlim/opt/anaconda3/lib/python3.8/urllib/request.py\", line 649, in http_error_default\n",
      "        raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "    urllib.error.HTTPError: HTTP Error 403: SSL is required\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/90/5a/ce7bef80825c2188cf507baf57b37516e18dffdb198a6766a597f703059a/MySQL-python-1.2.4.zip#sha256=e405f9d6be33923d428acaa4db4f4470427f1d15ea0d2d82a933449ace26bbd9 (from https://pypi.org/simple/mysql-python/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading MySQL-python-1.2.3.tar.gz (70 kB)\n",
      "\u001b[K     |████████████████████████████████| 70 kB 1.4 MB/s \n",
      "\u001b[?25h\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/seokjinlim/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_2e79c98eb208489d8f35d64313fde900/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_2e79c98eb208489d8f35d64313fde900/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-pip-egg-info-v24w3_6r\n",
      "         cwd: /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_2e79c98eb208489d8f35d64313fde900/\n",
      "    Complete output (8 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_2e79c98eb208489d8f35d64313fde900/setup.py\", line 11, in <module>\n",
      "        from setup_posix import get_config\n",
      "      File \"/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-ho24nfo0/mysql-python_2e79c98eb208489d8f35d64313fde900/setup_posix.py\", line 101\n",
      "        print \"\"\"You shouldn't be running this directly; it is used by setup.py.\"\"\"\n",
      "              ^\n",
      "    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(\"\"\"You shouldn't be running this directly)?\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9a/81/924d6799494cf7fb24370335c2f782088d6ac4f79e4137d4df94cea3582c/MySQL-python-1.2.3.tar.gz#sha256=7de66fbbf923634e7c965aeaefa74642ba75ae20ee1cefcefc3009595b7a7e6e (from https://pypi.org/simple/mysql-python/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31mERROR: Cannot install mysql==0.0.1 and mysql==0.0.2 because these package versions have conflicting dependencies.\u001b[0m\n",
      "\n",
      "The conflict is caused by:\n",
      "    mysql 0.0.2 depends on mysqlclient\n",
      "    mysql 0.0.1 depends on MySQL-python\n",
      "\n",
      "To fix this you could try to:\n",
      "1. loosen the range of package versions you've specified\n",
      "2. remove package versions to allow pip attempt to solve the dependency conflict\n",
      "\n",
      "\u001b[31mERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install mysql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "from datetime import date, datetime, timedelta\n",
    "import pandas as pd\n",
    "import pymysql\n",
    "from pykrx import stock"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "conn = pymysql.connect(\n",
    "    user='seokjin', \n",
    "    passwd='1234', \n",
    "    host='3.36.94.44', \n",
    "    db='stock', \n",
    "    charset='utf8'\n",
    ")\n",
    "cur = conn.cursor()\n",
    "try:\n",
    "    with conn.cursor() as curs:\n",
    "        sql = \"INSERT INTO stock.stock_kospi(`index`, code, code_name, check_item) VALUES(%s, %s, %s, 'Y')\"\n",
    "        print(curs.execute(sql_query))\n",
    "        result = curs.fetchall()\n",
    "        df = pd.DataFrame(result)\n",
    "except:\n",
    "\tprint(\"{} error\".format(sql_query))\n",
    "finally:\n",
    "    conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [],
   "source": [
    "tickers = stock.get_market_ticker_list()\n",
    "df = pd.DataFrame(tickers)\n",
    "# 종목 = stock.get_market_ticker_name(ticker)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "# df['code_name'] = stock.get_market_ticker_name(df[0])\n",
    "df.columns = ['a']\n",
    "# df['1'] = df['0']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [],
   "source": [
    "df['b'] = df['a']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "metadata": {},
   "outputs": [],
   "source": [
    "from datetime import date, datetime, timedelta\n",
    "import pandas as pd\n",
    "import pymysql\n",
    "import numpy as np\n",
    "from pykrx import stock"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "from datetime import date, datetime, timedelta\n",
    "import pandas as pd\n",
    "import pymysql\n",
    "import numpy as np\n",
    "from pykrx import stock\n",
    "\n",
    "ticker_count  = 0\n",
    "commit_count  = 0\n",
    "ticker_queue = []\n",
    "\n",
    "# Connect to the database\n",
    "connection = pymysql.connect(\n",
    "    user='seokjin', \n",
    "    passwd='1234', \n",
    "    host='3.36.94.44', \n",
    "    db='stock', \n",
    "    charset='utf8'\n",
    ")\n",
    "stock_lsits = ['KOSPI', 'KOSDAQ', 'ETF']\n",
    "cursor=connection.cursor()\n",
    "\n",
    "for stock_list in stock_lsits:\n",
    "    if stock_list != 'ETF':\n",
    "        tickers = stock.get_market_ticker_list(market=stock_list)\n",
    "    else:\n",
    "        tickers = stock.get_etf_ticker_list()\n",
    "\n",
    "\n",
    "    len_tickers = len(tickers)\n",
    "    tickers = np.array(tickers).reshape(len_tickers,-1)\n",
    "    ones = np.array([[stock_list,'Y',date.today().isoformat()]] * len_tickers)\n",
    "    tickers = np.append(tickers, ones, axis = 1)\n",
    "\n",
    "\n",
    "    commit_count = 0\n",
    "    ticker_count = 0\n",
    "\n",
    "\n",
    "    for ticker in tickers:\n",
    "        commit_count+=1\n",
    "        ticker_count+=1\n",
    "        ticker_queue.append(ticker.tolist())\n",
    "\n",
    "        if commit_count == 1000 or len_tickers == ticker_count:\n",
    "            cols = \"`,`\".join([str(i) for i in ['code', 'code_gbn', 'check_item', 'create_date']])\n",
    "            sql = \"INSERT INTO `stock_kospi` (`\" +cols + \"`) VALUES (\" + \"%s,\"*(ticker.shape[0]-1) + \"%s)  ON DUPLICATE KEY UPDATE update_date =\"+\"'\"+date.today().isoformat()+\"'\"\n",
    "            cursor.executemany(sql,ticker_queue)\n",
    "\n",
    "            connection.commit()\n",
    "            commit_count=0\n",
    "            ticker_queue = []\n",
    "\n",
    "\n",
    "cursor.close()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Collecting ta-lib\n",
      "  Downloading TA-Lib-0.4.20.tar.gz (266 kB)\n",
      "\u001b[K     |████████████████████████████████| 266 kB 1.6 MB/s \n",
      "\u001b[?25hRequirement already satisfied: numpy in /Users/seokjinlim/opt/anaconda3/lib/python3.8/site-packages (from ta-lib) (1.19.2)\n",
      "Building wheels for collected packages: ta-lib\n",
      "  Building wheel for ta-lib (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/seokjinlim/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-vx179j7r/ta-lib_807d9b6bc81b4053919fff48824ae916/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-vx179j7r/ta-lib_807d9b6bc81b4053919fff48824ae916/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-wheel-qlwtkgoa\n",
      "       cwd: /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-vx179j7r/ta-lib_807d9b6bc81b4053919fff48824ae916/\n",
      "  Complete output (28 lines):\n",
      "  /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-vx179j7r/ta-lib_807d9b6bc81b4053919fff48824ae916/setup.py:75: UserWarning: Cannot find ta-lib library, installation may fail.\n",
      "    warnings.warn('Cannot find ta-lib library, installation may fail.')\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  creating build\n",
      "  creating build/lib.macosx-10.9-x86_64-3.8\n",
      "  creating build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "  copying talib/abstract.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "  copying talib/test_abstract.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "  copying talib/deprecated.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "  copying talib/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "  copying talib/stream.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "  copying talib/test_pandas.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "  copying talib/test_data.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "  copying talib/test_func.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "  copying talib/test_stream.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "  running build_ext\n",
      "  skipping 'talib/_ta_lib.c' Cython extension (up-to-date)\n",
      "  building 'talib._ta_lib' extension\n",
      "  creating build/temp.macosx-10.9-x86_64-3.8\n",
      "  creating build/temp.macosx-10.9-x86_64-3.8/talib\n",
      "  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/seokjinlim/opt/anaconda3/include -arch x86_64 -I/Users/seokjinlim/opt/anaconda3/include -arch x86_64 -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/Users/seokjinlim/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include -I/Users/seokjinlim/opt/anaconda3/include/python3.8 -c talib/_ta_lib.c -o build/temp.macosx-10.9-x86_64-3.8/talib/_ta_lib.o\n",
      "  talib/_ta_lib.c:613:10: fatal error: 'ta-lib/ta_defs.h' file not found\n",
      "  #include \"ta-lib/ta_defs.h\"\n",
      "           ^~~~~~~~~~~~~~~~~~\n",
      "  1 error generated.\n",
      "  error: command 'gcc' failed with exit status 1\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[31m  ERROR: Failed building wheel for ta-lib\u001b[0m\n",
      "\u001b[?25h  Running setup.py clean for ta-lib\n",
      "Failed to build ta-lib\n",
      "Installing collected packages: ta-lib\n",
      "    Running setup.py install for ta-lib ... \u001b[?25lerror\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/seokjinlim/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-vx179j7r/ta-lib_807d9b6bc81b4053919fff48824ae916/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-vx179j7r/ta-lib_807d9b6bc81b4053919fff48824ae916/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-record-7_21cli1/install-record.txt --single-version-externally-managed --compile --install-headers /Users/seokjinlim/opt/anaconda3/include/python3.8/ta-lib\n",
      "         cwd: /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-vx179j7r/ta-lib_807d9b6bc81b4053919fff48824ae916/\n",
      "    Complete output (28 lines):\n",
      "    /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-vx179j7r/ta-lib_807d9b6bc81b4053919fff48824ae916/setup.py:75: UserWarning: Cannot find ta-lib library, installation may fail.\n",
      "      warnings.warn('Cannot find ta-lib library, installation may fail.')\n",
      "    running install\n",
      "    running build\n",
      "    running build_py\n",
      "    creating build\n",
      "    creating build/lib.macosx-10.9-x86_64-3.8\n",
      "    creating build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "    copying talib/abstract.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "    copying talib/test_abstract.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "    copying talib/deprecated.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "    copying talib/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "    copying talib/stream.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "    copying talib/test_pandas.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "    copying talib/test_data.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "    copying talib/test_func.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "    copying talib/test_stream.py -> build/lib.macosx-10.9-x86_64-3.8/talib\n",
      "    running build_ext\n",
      "    skipping 'talib/_ta_lib.c' Cython extension (up-to-date)\n",
      "    building 'talib._ta_lib' extension\n",
      "    creating build/temp.macosx-10.9-x86_64-3.8\n",
      "    creating build/temp.macosx-10.9-x86_64-3.8/talib\n",
      "    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/seokjinlim/opt/anaconda3/include -arch x86_64 -I/Users/seokjinlim/opt/anaconda3/include -arch x86_64 -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/Users/seokjinlim/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include -I/Users/seokjinlim/opt/anaconda3/include/python3.8 -c talib/_ta_lib.c -o build/temp.macosx-10.9-x86_64-3.8/talib/_ta_lib.o\n",
      "    talib/_ta_lib.c:613:10: fatal error: 'ta-lib/ta_defs.h' file not found\n",
      "    #include \"ta-lib/ta_defs.h\"\n",
      "             ^~~~~~~~~~~~~~~~~~\n",
      "    1 error generated.\n",
      "    error: command 'gcc' failed with exit status 1\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[31mERROR: Command errored out with exit status 1: /Users/seokjinlim/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-vx179j7r/ta-lib_807d9b6bc81b4053919fff48824ae916/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-install-vx179j7r/ta-lib_807d9b6bc81b4053919fff48824ae916/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /private/var/folders/fc/q2lr0h81353czp3nmr4hl9800000gn/T/pip-record-7_21cli1/install-record.txt --single-version-externally-managed --compile --install-headers /Users/seokjinlim/opt/anaconda3/include/python3.8/ta-lib Check the logs for full command output.\u001b[0m\n",
      "\u001b[33mWARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.\n",
      "You should consider upgrading via the '/Users/seokjinlim/opt/anaconda3/bin/python -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install ta-lib"
   ]
  }
 ]
}